stages:
    - test

variables:
    GO111MODULE: "on"

.test: &test_template
    stage: test
    services:
        - name: apache/couchdb:2.3.1
          alias: couch23
    variables:
        COUCHDB_USER: admin
        COUCHDB_PASSWORD: abc123
        KIVIK_TEST_DSN_COUCH23: http://admin:abc123@couch23:5984/
    before_script:
        - ./script/complete_couch2.sh ${KIVIK_TEST_DSN_COUCH23}
    script:
        - go mod download
        - ./script/test_version.sh
        - go test -race -tags=livetest ./...

lint:
    stage: test
    image: golang:1.13
    services: []
    before_script:
        - ''
    script:
        - go mod download
        - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.22.2
        - golangci-lint run ./...

coverage:
    stage: test
    image: golang:1.13
    services: []
    before_script:
        - ''
    script:
        - go mod download
        - ./script/coverage.sh

go-1.11:
    <<: *test_template
    stage: test
    image: golang:1.11

go-1.12:
    <<: *test_template
    stage: test
    image: golang:1.12

go-1.13:
    <<: *test_template
    stage: test
    image: golang:1.13

gopherjs-1.12:
    <<: *test_template
    stage: test
    image: golang:1.12
    script:
        - ( cd $GOPATH && GO111MODULE=off go get -u github.com/gopherjs/gopherjs )
        - curl -sL https://deb.nodesource.com/setup_6.x | bash -
        - apt-get update -qq && apt-get install -y nodejs npm
        - npm install
        - go get -u github.com/gopherjs/gopherjs
        - npm install source-map-support
        - |
            (
                cd $GOPATH/src/github.com/gopherjs/gopherjs/node-syscall/
                npm install --global node-gyp
                node-gyp rebuild
                mkdir -p ~/.node_libraries/
                cp build/Release/syscall.node ~/.node_libraries/syscall.node
            )
        - go mod download
        - gopherjs test ./...

go-rc:
    <<: *test_template
    stage: test
    image: golang:rc
    allow_failure: true
